create table CmsTranslation (programmeId varchar(255) not null, targetUrl varchar(2000), sourceUrlDigest varchar(32) not null, primary key (programmeId, sourceUrlDigest)) ENGINE=InnoDB;
create table Content (id bigint not null auto_increment, contentData longtext, contentDescId bigint not null, content_index integer, primary key (id)) ENGINE=InnoDB;
create table ContentDescriptor (id bigint not null auto_increment, url varchar(2000) not null, urlDigest varchar(32) not null, projectId bigint not null, primary key (id), unique (projectId, urlDigest)) ENGINE=InnoDB;
create table DocumentHandlerEntry (id varchar(255) not null, mimeType varchar(60), url varchar(2000), primary key (id)) ENGINE=InnoDB;
create table EventItem (id bigint not null auto_increment, action integer, activityDate datetime, targetId varchar(255), type integer, user_id bigint, primary key (id)) ENGINE=InnoDB;
create table ExportConfiguration (id bigint not null auto_increment, content longtext not null, createdDate datetime, name varchar(50) not null, restoreDate datetime, export_size integer, primary key (id)) ENGINE=InnoDB;
create table Job (id bigint not null auto_increment, completed datetime, started datetime, state varchar(25), throttled bit not null, projectId bigint not null, taskPipelineId varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table OutboundLink (id bigint not null auto_increment, url varchar(2000) not null, urlDigest varchar(32) not null, contentDescId bigint not null, primary key (id)) ENGINE=InnoDB;
create table Programme (id varchar(255) not null, customerName varchar(50), description varchar(255), inDevelopment bit not null, name varchar(50) not null unique, primary key (id)) ENGINE=InnoDB;
create table Project (type char(1) not null, id bigint not null auto_increment, description varchar(255), name varchar(50) not null unique, state varchar(25), subprojectType varchar(15), programmeId varchar(255), parentProjectId bigint, primary key (id), unique (parentProjectId, name)) ENGINE=InnoDB;
create table ProjectResource (id bigint not null auto_increment, contents longtext, name varchar(255), type varchar(20), projectId bigint not null, resource_index integer, primary key (id), unique (projectId, name)) ENGINE=InnoDB;
create table QueryDefinition (id bigint not null auto_increment, definition varchar(1000), description varchar(255), name varchar(255), qLibraryId bigint, primary key (id)) ENGINE=InnoDB;
create table QueryLibrary (id bigint not null auto_increment, name varchar(100) not null unique, primary key (id)) ENGINE=InnoDB;
create table RecentItem (id bigint not null auto_increment, activityDate datetime, taskDefinitionPath varchar(255), project_id bigint, queryDefinition_id bigint, taskPipeline_id varchar(255), user_id bigint, primary key (id)) ENGINE=InnoDB;
create table ScheduledJob (id varchar(255) not null, enabled bit not null, endTime datetime, intervalValue integer, intervalUnit varchar(25), jobId bigint, lastRunEndTime datetime, lastRunTime datetime, name varchar(255), startTime datetime, timeZone varchar(100), taskPipelineId varchar(255), primary key (id)) ENGINE=InnoDB;
create table TaskDescriptor (id bigint not null auto_increment, taskDefinitionPath varchar(255) not null, taskPipelineId varchar(255) not null, taskdescriptor_index integer, primary key (id)) ENGINE=InnoDB;
create table TaskPipeline (type char(1) not null, id varchar(255) not null, description varchar(255), name varchar(255), projectId bigint not null, taskpipeline_index integer, primary key (id)) ENGINE=InnoDB;
create table license (id varchar(255) not null, eventDate datetime, license longtext, primary key (id)) ENGINE=InnoDB;
create table metadata (contentDescId bigint not null, metadataValue varchar(4000), metadataName varchar(100) not null, primary key (contentDescId, metadataName)) ENGINE=InnoDB;
create table projectProperties (projectId bigint not null, propValue varchar(4000), propKey varchar(100) not null, primary key (projectId, propKey)) ENGINE=InnoDB;
create table redirection (projectId bigint not null, redirectedUrl varchar(2000), originalUrlDigest varchar(32) not null, primary key (projectId, originalUrlDigest)) ENGINE=InnoDB;
create table taskparameters (taskDescriptorId bigint not null, paramValue varchar(4000), paramKey varchar(100) not null, primary key (taskDescriptorId, paramKey)) ENGINE=InnoDB;
create table vuser (id bigint not null auto_increment, dateFormat varchar(20) not null unique, email varchar(70) not null unique, fullname varchar(200), lastAccessed datetime, loggedIn bit not null, password varchar(255), username varchar(50) not null unique, primary key (id)) ENGINE=InnoDB;
alter table CmsTranslation add index fk_Prog_CmsTrans (programmeId), add constraint fk_Prog_CmsTrans foreign key (programmeId) references Programme (id);
alter table Content add index fk_Content_ContentDescriptor (contentDescId), add constraint fk_Content_ContentDescriptor foreign key (contentDescId) references ContentDescriptor (id);
create index projectIdurlHash on ContentDescriptor (projectId, urlDigest);
alter table ContentDescriptor add index fk_Proj_CDesc (projectId), add constraint fk_Proj_CDesc foreign key (projectId) references Project (id);
alter table EventItem add index fk_User_EventItem (user_id), add constraint fk_User_EventItem foreign key (user_id) references vuser (id);
alter table Job add index fk_Job_TaskPipeline (taskPipelineId), add constraint fk_Job_TaskPipeline foreign key (taskPipelineId) references TaskPipeline (id);
alter table Job add index fk_Proj_Job (projectId), add constraint fk_Proj_Job foreign key (projectId) references Project (id);
alter table OutboundLink add index fk_CDesc_OutRef (contentDescId), add constraint fk_CDesc_OutRef foreign key (contentDescId) references ContentDescriptor (id);
alter table Project add index fk_SProj_MProj (parentProjectId), add constraint fk_SProj_MProj foreign key (parentProjectId) references Project (id);
alter table Project add index fk_MasterProject_Programme (programmeId), add constraint fk_MasterProject_Programme foreign key (programmeId) references Programme (id);
alter table ProjectResource add index fk_ProjectResource_Project (projectId), add constraint fk_ProjectResource_Project foreign key (projectId) references Project (id);
alter table QueryDefinition add index fk_QueryDefn_QueryLib (qLibraryId), add constraint fk_QueryDefn_QueryLib foreign key (qLibraryId) references QueryLibrary (id);
alter table RecentItem add index FK8BAA6C2E6FF02AEE (queryDefinition_id), add constraint FK8BAA6C2E6FF02AEE foreign key (queryDefinition_id) references QueryDefinition (id);
alter table RecentItem add index FK8BAA6C2E8B1C25C8 (taskPipeline_id), add constraint FK8BAA6C2E8B1C25C8 foreign key (taskPipeline_id) references TaskPipeline (id);
alter table RecentItem add index FK8BAA6C2EB1E9E10C (project_id), add constraint FK8BAA6C2EB1E9E10C foreign key (project_id) references Project (id);
alter table RecentItem add index fk_User_RecentItem (user_id), add constraint fk_User_RecentItem foreign key (user_id) references vuser (id);
alter table ScheduledJob add index fk_ScheduledJob_TaskPipeline (taskPipelineId), add constraint fk_ScheduledJob_TaskPipeline foreign key (taskPipelineId) references TaskPipeline (id);
alter table TaskDescriptor add index fk_TPipe_TDTPipe (taskPipelineId), add constraint fk_TPipe_TDTPipe foreign key (taskPipelineId) references TaskPipeline (id);
alter table TaskPipeline add index fk_Proj_TPipe (projectId), add constraint fk_Proj_TPipe foreign key (projectId) references Project (id);
alter table metadata add index FKE52D7B2F9EA3D6D2 (contentDescId), add constraint FKE52D7B2F9EA3D6D2 foreign key (contentDescId) references ContentDescriptor (id) ON DELETE CASCADE;
alter table projectProperties add index FK3E3692CF1FF32FF (projectId), add constraint FK3E3692CF1FF32FF foreign key (projectId) references Project (id);
alter table redirection add index FK757142ACF1FF32FF (projectId), add constraint FK757142ACF1FF32FF foreign key (projectId) references Project (id);
alter table taskparameters add index fk_TDesc_TPars (taskDescriptorId), add constraint fk_TDesc_TPars foreign key (taskDescriptorId) references TaskDescriptor (id);
